# **Import Numpy Library**

In [ ]:
import numpy as np

**https://www.w3resource.com/python-exercises/numpy/index-array.php**
- Numpy Questions: 4, 8, 9, 10, 12, 14, 19

**4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**
<br>[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<br>Update sixth value to 11
<br>[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [2]:
import numpy as np

In [12]:
a = np.zeros(10)
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
print("Update sixth value to 11")
a[6] = 11
a

Update sixth value to 11


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

**8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**
![image-4.png](attachment:image-4.png)

In [30]:
print("Original array:")
a = np.ones((5,5))
a

Original array:


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
print("1 on the border and 0 inside in the array")
a[1:4,1:(len(a)-1)] = 0
a

1 on the border and 0 inside in the array


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**9. Write a NumPy program to add a border (filled with 0's) around an existing array.**
![image-2.png](attachment:image-2.png)

In [36]:
print("Original array:")
a = np.ones((3,3))
a

Original array:


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
b = np.zeros((5,5))
b[1:4,1:4] = a
b

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
print("0 on the border and 1 inside in the array")

# ...

0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**
![image.png](attachment:image.png)

In [47]:
a = np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**12. Write a NumPy program to append values to the end of an array.**
![image-2.png](attachment:image-2.png)

In [58]:
print("Original array:")
a = np.array([10,20,30])
print(a)

Original array:
[10 20 30]


In [59]:
print("After append values to the end of the array:")
a = np.append(a,[40,50,60,70,80,90])
print(a)


After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


**14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.**
![image.png](attachment:image.png)

In [61]:
print("Values in Fahrenheit degrees:")
a= np.array([0,12,45.21,34,99.91])
a

Values in Fahrenheit degrees:


array([ 0.  , 12.  , 45.21, 34.  , 99.91])

In [63]:
print("Values in  Centigrade degrees:") 
print(5*a/9 - 5*32/9)


Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


**19. Write a NumPy program to get the unique elements of an array.**
![image.png](attachment:image.png)

In [65]:
print("Original array:")
a = np.array([10,10,20,20,30,30])
a

Original array:


array([10, 10, 20, 20, 30, 30])

In [67]:
print("Unique elements of the above array:")
b = np.unique(a)
b

Unique elements of the above array:


array([10, 20, 30])

In [78]:
print("Original array:")
a = np.array([[1,1],[2,3]])
a


Original array:


array([[1, 1],
       [2, 3]])

In [76]:
print("Unique elements of the above array:")
np.unique(a)


Unique elements of the above array:


array([1, 2, 3])

# **import Pandas Library**

In [ ]:
import pandas as pd

**https://www.w3resource.com/python-exercises/pandas/index-data-series.php**
- Pandas Questions: 2, 3, 5, 6, 13

**2. Write a Pandas program to convert a Pandas module Series to Python list and it's type.**

In [ ]:
list_1 = [2, 4, 6, 8, 10]

In [ ]:
# Convert the Python list to a Pandas Series 
print("Pandas Series and type")

# ...


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# Convert the Pandas Series to Python list

# ...


[2, 4, 6, 8, 10]
<class 'list'>


**3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.**

In [ ]:
list1 = [2, 4, 6, 8, 10]
list2 = [1, 3, 5, 7, 9]

In [ ]:
# Create two Pandas series with these lists

# ...


In [ ]:
print("Add two Series:")

# ...


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64


In [ ]:
print("Subtract two Series:")

# ...


Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64


In [ ]:
print("Multiply two Series:")

# ...


Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64


In [ ]:
print("Divide Series1 by Series2:")

# ...


Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


**5. Write a Pandas program to convert a dictionary to a Pandas series.**

In [ ]:
keys=['a','b','c','d','e']
values = [100, 200, 300, 400, 800]

In [ ]:
# Create a dictionary from keys and values
print("Original dictionary:")

# ...


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}


In [ ]:
# Convert the dictionary to a Pandas series
print("Converted series:")

# ...


Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


**6. Write a Pandas program to convert a NumPy array to a Pandas series.**

In [ ]:
# Original Data : [10, 20, 30, 40, 50]
# Create a numpy array with this data
print("NumPy array:")

# ...


NumPy array:
[10 20 30 40 50]


In [ ]:
# Convert a NumPy array to this Pandas series.
print("Converted Pandas series:")

# ...


Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int32


**12. Write a Pandas program to add some data to an existing Series.**|

In [ ]:
# Original Data : ['100', '200', 'python', '300.12', '400']
# Built a pandas Series with this data
print("Original Data Series:")
# ...

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [ ]:
# Add ['500', 'php'] to the original Data Series
print("\nData Series after adding some data:")

# ...



Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


**13. Write a Pandas program to create a subset of a given series based on value and condition.**

In [ ]:
# Original Data : [0,1,2,3,4,5,6,7,8,9,10]
# Built a pandas Series with this data
print("Original Data Series:")

# ...


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


In [ ]:
# Create a new series with data with a value less than 6
print("\nSubset of the above Data Series:")

# ...



Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
