## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples = np.random.normal(100,15,1000)

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = samples.mean()
median = np.median(samples)
mode = stats.mode(samples)

In [ ]:
print(' Mean: {}\n Median: {}\n Mode: {}'.format(mean,median,mode))

 Mean: 100.17053026777474
 Median: 99.56218050984377
 Mode: ModeResult(mode=array([60.83365074]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
samples.max()

148.06219700430694

In [ ]:
min = samples.min()
max = samples.max()
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3-q1

In [ ]:
print('Min: ',min,'\nMax: ',max,'\nq1: ',q1,'\nq3: ',q3,'\niqr: ',iqr)

Min:  60.83365074284536 
Max:  148.06219700430694 
q1:  90.11359170674825 
q3:  110.30296829741211 
iqr:  20.189376590663855


Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)

In [ ]:
print('Variance: {}\nStd: {}'.format(variance,std_dev))

Variance: 222.88890092469
Std: 14.929464187461317


Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)

kurtosis = stats.kurtosis(samples)

In [ ]:
print('Skewness: {}\nKurtosis: {}'.format(skewness,kurtosis))

Skewness: 0.12085234994614222
Kurtosis: -0.048618516300255266


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(11,21)
x

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.random.randint(1,21,10)
y

array([12, 19,  6,  5,  1,  3,  3,  6, 13, 14])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
np.cov(x, y)

array([[  9.16666667,  68.16666667],
       [ 68.16666667, 880.76666667]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r, p = stats.pearsonr(x, y)
r

0.758640289091187

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000