In [1]:
import numpy as np

In [2]:
np.arange(1,5)

array([1, 2, 3, 4])

In [7]:
np.linspace(1,20,5,retstep=True)

(array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]), 4.75)

In [11]:
np.random.random_sample(5)

array([0.17410376, 0.51177722, 0.90740179, 0.72489752, 0.31929277])

In [44]:
np.random.randint(10,20)

14

In [12]:
np.random.rand(3,3)

array([[0.82381243, 0.05761307, 0.22981175],
       [0.76141565, 0.9418263 , 0.32340612],
       [0.55843786, 0.57322108, 0.285665  ]])

In [29]:
np.random.randint(10,size=(5,5))

array([[9, 0, 8, 1, 0],
       [6, 3, 6, 8, 1],
       [6, 9, 6, 4, 2],
       [4, 7, 7, 3, 6],
       [2, 9, 9, 3, 5]])

In [28]:
my_arr = np.arange(10).reshape(2,5)
np.random.shuffle(my_arr)
my_arr

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [30]:
s = (3,3)
np.zeros(s)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.max(np.random.random_sample(10))

0.9239149238785347

In [36]:
np.min(np.random.random_sample(10))

0.03555342719247423

In [37]:
np.argmax(np.random.random_sample(10))

1

In [42]:
np.argmin(np.random.random_sample(10))

3

In [56]:
np.ndim([[[1,2,3],[4,5,6]]])

3

In [58]:

np.size(np.arange(10,15,2))

3

In [64]:
np.split(np.arange(10,20),2)

[array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]

In [65]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
np.vstack((a,b))


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [68]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
c = np.hstack((a,b))
c


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [70]:
d = c > 5
d

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True]])

In [71]:
c[d]

array([ 6,  7,  8,  9, 10, 11])

In [74]:
c[d] = -1
c

array([[ 0,  1, -1, -1],
       [ 2,  3, -1, -1],
       [ 4,  5, -1, -1]])

In [75]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))

In [76]:
arr_2d[:1,1:]

array([[10, 15]])