In [2]:
import numpy as np

In [2]:
my_list = [1,5,2,7]

In [3]:
np.array(my_list)

array([1, 5, 2, 7])

In [5]:
a = [1,6,2,8]
b = [6,21,24,5]
ab = []
for i in range(0,len(a)):
  ab.append(a[i]*b[i])
ab

[6, 126, 48, 40]

In [11]:
a1 = np.array([1,72,46,234])
a2 = np.array([23,63,11,23])
a1*a2

array([  23, 4536,  506, 5382])

In [10]:
a1.ndim

3

In [13]:
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
b = np.array([[8,7,6],[5,4,3],[3,2,1]])
a*b

array([[ 8, 14, 18],
       [15, 16, 15],
       [18, 14,  8]])

In [18]:
a = [[2,3,123],[2,313,23],[2,313,1]]
np.array(a)


array([[  2,   3, 123],
       [  2, 313,  23],
       [  2, 313,   1]])

In [22]:
np.arange(11,0,-1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [25]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.full((3,3),'np',order='C')

array([['np', 'np', 'np'],
       ['np', 'np', 'np'],
       ['np', 'np', 'np']], dtype='<U2')

In [35]:
np.linspace(12,3,4,endpoint=False)

array([12.  ,  9.75,  7.5 ,  5.25])

In [48]:
np.eye(5,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [64]:
np.random.randint(5,15,size=(3,3))

array([[ 6,  7,  9],
       [14, 11, 14],
       [13,  9, 10]])

In [4]:
np.random.randint(1,11,size=(4,4))

array([[1, 1, 4, 4],
       [9, 3, 3, 4],
       [6, 1, 3, 9],
       [5, 5, 8, 3]])

In [ ]:
np.random.randint(2,[4,8,11])

In [35]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
rand = np.random.randint(2,10,size=(4,4))
rand

array([[5, 5, 8, 8],
       [3, 2, 9, 6],
       [9, 8, 8, 2],
       [2, 6, 6, 9]])

In [36]:
np.concatenate([ones,rand])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [5., 5., 8., 8.],
       [3., 2., 9., 6.],
       [9., 8., 8., 2.],
       [2., 6., 6., 9.]])

In [37]:
np.concatenate([ones,rand],axis=1)

array([[1., 1., 1., 1., 5., 5., 8., 8.],
       [1., 1., 1., 1., 3., 2., 9., 6.],
       [1., 1., 1., 1., 9., 8., 8., 2.],
       [1., 1., 1., 1., 2., 6., 6., 9.]])

In [40]:
concat =  np.arange(1,26).reshape(5,5)
concat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
np.split(concat,[1,3])

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [42]:
concat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
np.split(concat,[3],axis=1)

[array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18],
        [21, 22, 23]]), array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]])]

In [45]:
m = np.arange(20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
np.vsplit(m, [1, 3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [47]:
upper, lower = np.vsplit(m, [3])

In [48]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
np.vsplit(m, 5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [53]:
np.hsplit()

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [54]:
v = np.array([2,1,4,3,5])

v

array([2, 1, 4, 3, 5])

In [55]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [56]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [57]:
df = sns.load_dataset("diamonds")
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [58]:
diamond = np.array(df[["carat","depth","price","x","y","z"]])
diamond

array([[2.300e-01, 6.150e+01, 3.260e+02, 3.950e+00, 3.980e+00, 2.430e+00],
       [2.100e-01, 5.980e+01, 3.260e+02, 3.890e+00, 3.840e+00, 2.310e+00],
       [2.300e-01, 5.690e+01, 3.270e+02, 4.050e+00, 4.070e+00, 2.310e+00],
       ...,
       [7.000e-01, 6.280e+01, 2.757e+03, 5.660e+00, 5.680e+00, 3.560e+00],
       [8.600e-01, 6.100e+01, 2.757e+03, 6.150e+00, 6.120e+00, 3.740e+00],
       [7.500e-01, 6.220e+01, 2.757e+03, 5.830e+00, 5.870e+00, 3.640e+00]])

In [64]:
diamond[1:3,1]

array([59.8, 56.9])

In [65]:
diamond[0:2,1 ]

array([61.5, 59.8])

In [66]:
diamond[0,::2]

array([2.30e-01, 3.26e+02, 3.98e+00])

In [67]:
xyz = diamond[:,-3:].reshape(len(diamond),3)
xyz

array([[3.95, 3.98, 2.43],
       [3.89, 3.84, 2.31],
       [4.05, 4.07, 2.31],
       ...,
       [5.66, 5.68, 3.56],
       [6.15, 6.12, 3.74],
       [5.83, 5.87, 3.64]])

In [68]:
volume = xyz[:,0]*xyz[:,1]*xyz[:,2]
volume.reshape(len(volume),1)

array([[ 38.20203 ],
       [ 34.505856],
       [ 38.076885],
       ...,
       [114.449728],
       [140.76612 ],
       [124.568444]])

In [69]:
a = np.arange(0,10)
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
b = np.arange(0,10).reshape(2,5)
b[:,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
b[0][1:4]

array([1, 2, 3])